# Generated by Django 5.2 on 2025-05-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_zone_parkingspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='spot_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='zone',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='spot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspot'),
            preserve_default=False,
        ),
    ]
