# Generated by Django 5.2 on 2025-05-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_remove_reservation_spot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
