# Generated by Django 5.2 on 2025-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_reservation_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
