# Generated by Django 5.2 on 2025-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingspot_latitude_parkingspot_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='landmark_hint',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
