# Generated by Django 5.2 on 2025-06-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parkingspot_landmark_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
