# Generated by Django 5.2 on 2025-05-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_of_birth_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
