# Generated by Django 5.2 on 2025-06-03 15:46

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_plate_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
